- id: 1
  role: director
  token: directordirectordirectordirectordirector
- id: 2
  role: agent
  token: role1role1role1role1role1role1role1role1
- id: 3
  role: agent
  token: role2role2role2role2role2role2role2role2
