- name: 1
  role: director
  character: 1
  token: directordirectordirectordirectordirector
- name: 2
  role: agent
  character: 2
  token: role1role1role1role1role1role1role1role1
- name: 3
  role: agent
  character: 2
  token: role2role2role2role2role2role2role2role2
