- name: 1
  role: director
  character: director
  token: directordirectordirectordirectordirector
- name: 2
  role: agent
  character: actor
  token: role1role1role1role1role1role1role1role1
- name: 3
  role: agent
  character: actor
  token: role2role2role2role2role2role2role2role2
