director:
- key:
    type: action
    namespace: xo-namespace
  methods:
  - watch
- key:
    type: world
    name: referee
    namespace: xo-namespace
  methods:
  - put
  - get


actors:
  agent:
  - key:
      type: world
      name: referee
      namespace: xo-namespace
    methods:
    - get
  - key:
      type: action
      namespace: xo-namespace
    methods:
    - put



