director:
- key:
    type: action
    namespace: xo-namespace
  methods:
  - 6
- key:
    type: world
    name: referee
    namespace: xo-namespace
  methods:
  - 3
  - 1


actors:
  agent:
  - key:
      type: world
      name: referee
      namespace: xo-namespace
    methods:
    - 1
  - key:
      type: action
      namespace: xo-namespace
    methods:
    - 3